pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'cd challenges/02-add-missing-stage && pip3 install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'cd challenges/02-add-missing-stage && python3 -m pytest test_app.py -v'
            }
        }
        stage('Run') {
            steps {
                sh 'cd challenges/02-add-missing-stage && python3 app.py'
            }
        }
    }
}
