"""Generate a tiny HTML report for the plugins demo."""

from pathlib import Path

REPORT = Path(__file__).resolve().parent / "report.html"

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Jenkins Plugins Demo Report</title>
  <style>
    body { font-family: Georgia, serif; margin: 2rem; background: #f7f4ef; color: #1a1a1a; }
    h1 { font-size: 1.6rem; }
    p { max-width: 40rem; line-height: 1.5; }
    .ok { color: #0b6e4f; font-weight: bold; }
  </style>
</head>
<body>
  <h1>Jenkins Plugins Demo</h1>
  <p>This page was generated by the pipeline and published with the
     <strong>HTML Publisher</strong> plugin.</p>
  <p class="ok">Report published successfully.</p>
</body>
</html>
"""


def main():
    REPORT.write_text(HTML, encoding="utf-8")
    print(f"Wrote {REPORT.name}")


if __name__ == "__main__":
    main()
