pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'cd challenges/01-fix-failing-tests && pip3 install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'cd challenges/01-fix-failing-tests && python3 -m pytest test_math_utils.py -v'
            }
        }
    }
}
