pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'cd challenges/01-create-pipeline-job && pip3 install --break-system-packages -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'cd challenges/01-create-pipeline-job && python3 -m pytest test_math_utils.py -v'
            }
        }
    }
}
