pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh '''
                    cd challenges/01-create-pipeline-job
                    python3 -m venv .venv
                    .venv/bin/pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'cd challenges/01-create-pipeline-job && .venv/bin/python -m pytest test_math_utils.py -v'
            }
        }
    }
}
